// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-animation/FloatingCoins.tsx": () => import("../components/mockups/hero-animation/FloatingCoins.tsx"),
  "./components/mockups/hero-animation/GraphRise.tsx": () => import("../components/mockups/hero-animation/GraphRise.tsx"),
  "./components/mockups/hero-animation/ParticleBurst.tsx": () => import("../components/mockups/hero-animation/ParticleBurst.tsx")
};
